services:
  lambda:
    build: .
    depends_on:
      postgres:
        condition: service_healthy
  postgres:
    image: postgres
    env_file: .env
      # volumes:
      #  - ./data:/var/lib/postgresql/data
    user: "${UID}:${GID}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 10s
      timeout: 5s
      retries: 5
